version: "3.8"

services:
  app:
    build: .
    container_name: app
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db 
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - my_network

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
